<?php

namespace Database\Seeders;

use App\Models\Booking;
use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Booking::factory()->createMany([
            array(
                'room_id' => 2,
                'user_id' => 1,
                'check_in_date' => '2023-12-22',
                'check_out_date' => '1986-12-25',
                'client_first_name' => 'Алексей',
                'client_last_name' => 'Смирнов',
                'client_middle_name' => 'Петрович',
                'client_phone' => '+987654321',
                'client_email' => 'alexey.smirnov@example.com',
                'promo_code' => '',
                'client_wishes' => 'Предпочтительно без ковра в номере.',
                'guests_count' => 3,
                'status' => 'отменено',
                'total_price' => 2370.87,
            ),
            array(
                'room_id' => 5,
                'user_id' => 1,
                'check_in_date' => '2023-12-15',
                'check_out_date' => '2023-12-20',
                'client_first_name' => 'Мария',
                'client_last_name' => 'Сидорова',
                'client_middle_name' => 'Алексеевна',
                'client_phone' => '+111222333',
                'client_email' => 'maria.sidorova@example.com',
                'promo_code' => '',
                'client_wishes' => 'Желательно тихий номер.',
                'guests_count' => 4,
                'status' => 'подтверждено',
                'total_price' => 3830.47,
            ),
            array(
                'room_id' => 10,
                'user_id' => 1,
                'check_in_date' => '2023-12-11',
                'check_out_date' => '2023-12-14',
                'client_first_name' => 'Елена',
                'client_last_name' => 'Петрова',
                'client_middle_name' => 'Иванова',
                'client_phone' => '+999888777',
                'client_email' => 'elena.petrova@example.com',
                'promo_code' => '',
                'client_wishes' => '',
                'guests_count' => 1,
                'status' => 'забронировано',
                'total_price' => 4940.66,
            ),
            array(
                'room_id' => 1,
                'user_id' => 1,
                'check_in_date' => '2023-10-20',
                'check_out_date' => '2003-10-27',
                'client_first_name' => 'Анна',
                'client_last_name' => 'Ковалева',
                'client_middle_name' => 'Сергеевна',
                'client_phone' => '+444555666',
                'client_email' => 'anna.kovaleva@example.com',
                'promo_code' => 'XYZ789',
                'client_wishes' => 'Необходим дополнительный комплект полотенец.',
                'guests_count' => 1,
                'status' => 'подтверждено',
                'total_price' => 1934.66,
            ),
            array(
                'room_id' => 9,
                'user_id' => 1,
                'check_in_date' => '2023-11-25',
                'check_out_date' => '2012-11-27',
                'client_first_name' => 'Михаил',
                'client_last_name' => 'Козлов',
                'client_middle_name' => 'Игоревич',
                'client_phone' => '+777888999',
                'client_email' => 'mikhail.kozlov@example.com',
                'promo_code' => '',
                'client_wishes' => 'Нужно дополнительное одеяло.',
                'guests_count' => 2,
                'status' => 'забронировано',
                'total_price' => 2885.11,
            ),
            array(
                'room_id' => 3,
                'user_id' => 1,
                'check_in_date' => '2023-12-01',
                'check_out_date' => '2023-12-10',
                'client_first_name' => 'Екатерина',
                'client_last_name' => 'Морозова',
                'client_middle_name' => 'Алексеевна',
                'client_phone' => '+666777888',
                'client_email' => 'ekaterina.morozova@example.com',
                'promo_code' => 'DEF456',
                'client_wishes' => 'Хотелось бы номер с балконом.',
                'guests_count' => 2,
                'status' => 'подтверждено',
                'total_price' => 1765.90,
            ),
            array(
                'room_id' => 8,
                'user_id' => 1,
                'check_in_date' => '2023-11-12',
                'check_out_date' => '2023-11-14',
                'client_first_name' => 'Андрей',
                'client_last_name' => 'Васильев',
                'client_middle_name' => 'Николаевич',
                'client_phone' => '+555666777',
                'client_email' => 'andrey.vasilyev@example.com',
                'promo_code' => '',
                'client_wishes' => '',
                'guests_count' => 2,
                'status' => 'забронировано',
                'total_price' => 2690.55,
            ),
            array(
                'room_id' => 7,
                'user_id' => 1,
                'check_in_date' => '2023-11-01',
                'check_out_date' => '2023-11-07',
                'client_first_name' => 'Ольга',
                'client_last_name' => 'Попова',
                'client_middle_name' => 'Иванова',
                'client_phone' => '+444555666',
                'client_email' => 'olga.popova@example.com',
                'promo_code' => '',
                'client_wishes' => '',
                'guests_count' => 1,
                'status' => 'подтверждено',
                'total_price' => 2710.21,
            ),
            array(
                'room_id' => 6,
                'user_id' => 1,
                'check_in_date' => '2023-11-28',
                'check_out_date' => '2023-11-30',
                'client_first_name' => 'Дмитрий',
                'client_last_name' => 'Соколов',
                'client_middle_name' => 'Александрович',
                'client_phone' => '+333444555',
                'client_email' => 'dmitry.sokolov@example.com',
                'promo_code' => '',
                'client_wishes' => '',
                'guests_count' => 2,
                'status' => 'подтверждено',
                'total_price' => 2555.55,
            ),
        ]);
    }
}
