<?php

namespace Database\Seeders;

use App\Models\Booking;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Booking::factory()->createMany([

            array(
                "id" => 14,
                "room_id" => 4,
                "user_id" => 6,
                "check_in_date" => "2023-10-03",
                "check_out_date" => "2023-10-24",
                "client_first_name" => "Иван",
                "client_last_name" => "Иванов",
                "client_patronymic" => "Иванович",
                "client_phone" => "+123456789",
                "client_email" => "ivan.ivanov@example.com",
                "client_promo_code" => "ABC123",
                "client_wishes" => "Хотелось бы номер с видом на море.",
                "client_guests_count" => 3,
                "status" => "отменено",
            ),
            array(
                "id" => 15,
                "room_id" => 2,
                "user_id" => 1,
                "check_in_date" => "2023-10-03",
                "check_out_date" => "1986-12-20",
                "client_first_name" => "Алексей",
                "client_last_name" => "Смирнов",
                "client_patronymic" => "Петрович",
                "client_phone" => "+987654321",
                "client_email" => "alexey.smirnov@example.com",
                "client_promo_code" => "",
                "client_wishes" => "Предпочтительно без ковра в номере.",
                "client_guests_count" => 3,
                "status" => "отменено",
            ),
            array(
                "id" => 16,
                "room_id" => 5,
                "user_id" => 6,
                "check_in_date" => "2023-10-09",
                "check_out_date" => "2023-10-20",
                "client_first_name" => "Мария",
                "client_last_name" => "Сидорова",
                "client_patronymic" => "Алексеевна",
                "client_phone" => "+111222333",
                "client_email" => "maria.sidorova@example.com",
                "client_promo_code" => "",
                "client_wishes" => "Желательно тихий номер.",
                "client_guests_count" => 4,
                "status" => "подтверждено",
            ),
            array(
                "id" => 17,
                "room_id" => 10,
                "user_id" => 1,
                "check_in_date" => "2023-10-01",
                "check_out_date" => "2023-10-03",
                "client_first_name" => "Елена",
                "client_last_name" => "Петрова",
                "client_patronymic" => "Иванова",
                "client_phone" => "+999888777",
                "client_email" => "elena.petrova@example.com",
                "client_promo_code" => "",
                "client_wishes" => "",
                "client_guests_count" => 4,
                "status" => "забронировано",
            ),
            array(
                "id" => 18,
                "room_id" => 1,
                "user_id" => 1,
                "check_in_date" => "2023-10-11",
                "check_out_date" => "2003-11-12",
                "client_first_name" => "Анна",
                "client_last_name" => "Ковалева",
                "client_patronymic" => "Сергеевна",
                "client_phone" => "+444555666",
                "client_email" => "anna.kovaleva@example.com",
                "client_promo_code" => "XYZ789",
                "client_wishes" => "Необходим дополнительный комплект полотенец.",
                "client_guests_count" => 1,
                "status" => "подтверждено",
            ),
            array(
                "id" => 19,
                "room_id" => 9,
                "user_id" => 9,
                "check_in_date" => "2023-10-05",
                "check_out_date" => "2012-10-10",
                "client_first_name" => "Михаил",
                "client_last_name" => "Козлов",
                "client_patronymic" => "Игоревич",
                "client_phone" => "+777888999",
                "client_email" => "mikhail.kozlov@example.com",
                "client_promo_code" => "",
                "client_wishes" => "Нужно дополнительное одеяло.",
                "client_guests_count" => 3,
                "status" => "забронировано",
            ),
            array(
                "id" => 20,
                "room_id" => 3,
                "user_id" => 8,
                "check_in_date" => "2023-10-01",
                "check_out_date" => "2023-10-20",
                "client_first_name" => "Екатерина",
                "client_last_name" => "Морозова",
                "client_patronymic" => "Алексеевна",
                "client_phone" => "+666777888",
                "client_email" => "ekaterina.morozova@example.com",
                "client_promo_code" => "DEF456",
                "client_wishes" => "Хотелось бы номер с балконом.",
                "client_guests_count" => 2,
                "status" => "подтверждено",
            ),
            array(
                "id" => 21,
                "room_id" => 8,
                "user_id" => 7,
                "check_in_date" => "2023-10-01",
                "check_out_date" => "2023-10-07",
                "client_first_name" => "Андрей",
                "client_last_name" => "Васильев",
                "client_patronymic" => "Николаевич",
                "client_phone" => "+555666777",
                "client_email" => "andrey.vasilyev@example.com",
                "client_promo_code" => "",
                "client_wishes" => "",
                "client_guests_count" => 2,
                "status" => "забронировано",
            ),
            array(
                "id" => 22,
                "room_id" => 7,
                "user_id" => 3,
                "check_in_date" => "2023-10-01",
                "check_out_date" => "2023-10-07",
                "client_first_name" => "Ольга",
                "client_last_name" => "Попова",
                "client_patronymic" => "Иванова",
                "client_phone" => "+444555666",
                "client_email" => "olga.popova@example.com",
                "client_promo_code" => "",
                "client_wishes" => "",
                "client_guests_count" => 1,
                "status" => "подтверждено",
            ),
            array(
                "id" => 23,
                "room_id" => 6,
                "user_id" => 5,
                "check_in_date" => "2023-09-24",
                "check_out_date" => "2023-09-30",
                "client_first_name" => "Дмитрий",
                "client_last_name" => "Соколов",
                "client_patronymic" => "Александрович",
                "client_phone" => "+333444555",
                "client_email" => "dmitry.sokolov@example.com",
                "client_promo_code" => "",
                "client_wishes" => "",
                "client_guests_count" => 2,
                "status" => "подтверждено",
            ),
        ]);
    }
}
