<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    /**
     * room_type_id равный 1 соответствует 
     * типу номера STANDARD и так далее
     * 
     * view_type_id равный 1 соответствует 
     * SEA и так далее
     * 
     * bed_type_id равный 1 соответствует
     * SINGLE и так далее
     */
    public function run(): void
    {
        Room::factory()->createMany([
            array(
                'hotel_id' => 1,
                'room_number' => '101',
                'description' => 'Уютный и бюджетный выбор для вашего пребывания.',
                'area' => 27,
                'apartment_count' => 1,
                'price' => 1270.87,
                'availability' => 'true',
                'adults_max_guests' => 1,
                'children_max_guests' => 0,
                'room_type_id' => 1,
                'view_type_id' => 2,
                'bed_type_id' => 1,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '102',
                'description' => 'Просто, но приглашающе, наш стандартный номер предлагает уютный отдых',
                'area' => 28,
                'apartment_count' => 1,
                'price' => 1383.79,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 1,
                'view_type_id' => 2,
                'bed_type_id' => 2,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '103',
                'description' => 'Расслабьтесь в нашем стандартном номере со всеми необходимыми удобствами.',
                'area' => 38,
                'apartment_count' => 2,
                'price' => 1540.13,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 1,
                'view_type_id' => 3,
                'bed_type_id' => 6,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '104',
                'description' => 'Идеальный выбор для путешественников, ищущих доступность и комфорт.',
                'area' => 31,
                'apartment_count' => 1,
                'price' => 1670.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 1,
                'view_type_id' => 4,
                'bed_type_id' => 5,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '105',
                'description' => 'Отдохните в нашем стандартном номере после дня исследований.',
                'area' => 41,
                'apartment_count' => 2,
                'price' => 1711.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 1,
                'view_type_id' => 1,
                'bed_type_id' => 7,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '201',
                'description' => 'Почувствуйте роскошь и расслабьтесь в нашем улучшенном номере.',
                'area' => 33,
                'apartment_count' => 1,
                'price' => 2370.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 2,
                'view_type_id' => 2,
                'bed_type_id' => 2,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '202',
                'description' => 'Повысьте уровень своего пребывания в нашем просторном и стильном улучшенном номере',
                'area' => 39,
                'apartment_count' => 2,
                'price' => 2470.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 2,
                'view_type_id' => 2,
                'bed_type_id' => 6,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '203',
                'description' => 'Позвольте себе дополнительный комфорт и удобства в нашем улучшенном номере.',
                'area' => 32,
                'apartment_count' => 1,
                'price' => 2583.79,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 1,
                'room_type_id' => 2,
                'view_type_id' => 3,
                'bed_type_id' => 4,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '204',
                'description' => 'Наш улучшенный номер предлагает премиальное пространство для требовательных гостей.',
                'area' => 38,
                'apartment_count' => 1,
                'price' => 2670.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 2,
                'view_type_id' => 4,
                'bed_type_id' => 3,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '205',
                'description' => 'Насладитесь высшим уровнем комфорта и элегантности в нашем улучшенном номере.',
                'area' => 40,
                'apartment_count' => 2,
                'price' => 2748.95,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 1,
                'room_type_id' => 2,
                'view_type_id' => 1,
                'bed_type_id' => 5,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '301',
                'description' => 'Почувствуйте великолепие роскоши в нашем премиум номере.',
                'area' => 34,
                'apartment_count' => 1,
                'price' => 3211.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 3,
                'view_type_id' => 2,
                'bed_type_id' => 2,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '302',
                'description' => 'Элегантность, утонченность и обслуживание на высшем уровне ждут вас в нашем премиум номере.',
                'area' => 42,
                'apartment_count' => 2,
                'price' => 3370.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 3,
                'view_type_id' => 2,
                'bed_type_id' => 6,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '303',
                'description' => 'Насладитесь роскошью и расслабьтесь в нашем премиум номере.',
                'area' => 42,
                'apartment_count' => 2,
                'price' => 3411.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 3,
                'room_type_id' => 3,
                'view_type_id' => 3,
                'bed_type_id' => 9,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '304',
                'description' => 'Наш премиум номер предлагает высший уровень размещения для взыскательных гостей.',
                'area' => 37,
                'apartment_count' => 1,
                'price' => 3554.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 1,
                'room_type_id' => 3,
                'view_type_id' => 4,
                'bed_type_id' => 5,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '305',
                'description' => 'Порадуйте себя пребыванием в нашем премиум номере для незабываемого отдыха.',
                'area' => 43,
                'apartment_count' => 1,
                'price' => 3670.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 3,
                'view_type_id' => 1,
                'bed_type_id' => 3,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '401',
                'description' => 'Поднимите свое пребывание на самый высший уровень роскоши в нашем люксе.',
                'area' => 38,
                'apartment_count' => 1,
                'price' => 4283.79,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 4,
                'view_type_id' => 2,
                'bed_type_id' => 2,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '402',
                'description' => 'Наслаждайтесь великолепием нашего роскошного и просторного номера.',
                'area' => 40,
                'apartment_count' => 1,
                'price' => 4311.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 1,
                'room_type_id' => 4,
                'view_type_id' => 2,
                'bed_type_id' => 5,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '403',
                'description' => 'Наш номер люкс предлагает захватывающие виды и уникальный дизайн.',
                'area' => 42,
                'apartment_count' => 1,
                'price' => 4511.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 0,
                'room_type_id' => 4,
                'view_type_id' => 3,
                'bed_type_id' => 3,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '404',
                'description' => 'Расслабьтесь в мире комфорта и стиля в нашем номере люкс.',
                'area' => 44,
                'apartment_count' => 2,
                'price' => 4683.79,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 4,
                'view_type_id' => 4,
                'bed_type_id' => 6,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '405',
                'description' => 'Почувствуйте роскошь жизни в нашем роскошном люксе.',
                'area' => 46,
                'apartment_count' => 2,
                'price' => 4800.23,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 4,
                'view_type_id' => 1,
                'bed_type_id' => 7,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '501',
                'description' => 'Просторные и подходящие для семей номера идеальны для всех.',
                'area' => 45,
                'apartment_count' => 1,
                'price' => 5370.87,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 1,
                'room_type_id' => 5,
                'view_type_id' => 2,
                'bed_type_id' => 4,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '502',
                'description' => 'Находите качественное время с близкими в нашем семейном дружелюбном пространстве.',
                'area' => 46,
                'apartment_count' => 1,
                'price' => 5411.84,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 1,
                'room_type_id' => 5,
                'view_type_id' => 2,
                'bed_type_id' => 5,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '503',
                'description' => 'Наши семейные номера предоставляют достаточно места для отдыха каждого.',
                'area' => 48,
                'apartment_count' => 2,
                'price' => 5572.81,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 5,
                'view_type_id' => 3,
                'bed_type_id' => 6,
            ),
            array(
                'hotel_id' => 1,
                'room_number' => '504',
                'description' => 'Создавайте незабываемые моменты в наших комфортабельных семейных номерах.',
                'area' => 50,
                'apartment_count' => 2,
                'price' => 5885.26,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 2,
                'room_type_id' => 5,
                'view_type_id' => 4,
                'bed_type_id' => 7,
            ),
            array(
                'id' => 25,
                'hotel_id' => 1,
                'room_number' => '505',
                'description' => 'Дом вдали от дома: наши семейные номера спроектированы для вашей семьи.',
                'area' => 56,
                'apartment_count' => 3,
                'price' => 5962.55,
                'availability' => 'true',
                'adults_max_guests' => 2,
                'children_max_guests' => 3,
                'room_type_id' => 5,
                'view_type_id' => 1,
                'bed_type_id' => 8,
            ),
        ]);
    }
}
